name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Clona el repositorio
      - name: Check out the code
        uses: actions/checkout@v3

      # Configura Docker Buildx (para soporte de múltiples plataformas)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Inicia sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construye y sube la imagen a Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ReyMarroquin/docker-hub:latest
